---

- job:
    name: galaxy-tox
    parent: tox
    vars:
      tox_envlist: ALL
    nodeset:
      nodes:
        - name: testvm
          label: dib-fedora-27

- project:
    check:
      jobs:
        - galaxy-tox

    gate:
      jobs:
        - galaxy-tox
