---

- job:
    name: galaxy-tox
    pre-run: .zuul-playbooks/galaxy-tox/pre.yaml
    run: .zuul-playbooks/galaxy-tox/run.yaml
    nodeset:
      nodes:
        - name: testvm
          label: dib-fedora-27

- project:
    check:
      jobs:
        - galaxy-tox

    gate:
      jobs:
        - galaxy-tox
