---

- hosts: all

  tasks:
    - shell: dnf remove -y docker docker-common container-selinux docker-selinux docker-engine
    - shell: dnf -y install curl
    - shell: curl -o /etc/yum.repos.d/docker-ce.repo https://download.docker.com/linux/fedora/docker-ce.repo
    - shell: dnf -y install docker-ce

    - shell: type tox || pip install --user tox

    - command: tox
      args:
        chdir: "{{ zuul.project.src_dir }}"
