---

- hosts: all

  tasks:
    - shell: dnf remove -y docker docker-common container-selinux docker-selinux docker-engine
      become: yes
    - shell: dnf -y install dnf-plugins-core
      become: yes
    - shell: dnf config-manager -add-repo https://download.docker.com/linux/fedora/docker-ce.repo
      become: yes
    - shell: dnf -y install docker-ce
      become: yes

    - shell: type tox || pip install --user tox

    - command: tox
      args:
        chdir: "{{ zuul.project.src_dir }}"
