---

- hosts: all

  tasks:
    - shell: dnf -y install dnf-plugins-core
      become: yes
    - shell: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
      become: yes
    - shell: dnf -y install docker-ce
      become: yes
    - shell: systemctl start docker
      become: yes
    - shell: pwd
    - shell: usermod -aG docker zuul-worker
      become: yes
    - shell: newgrp docker
      become: yes
    - shell: docker run hello-world

    - shell: type tox || pip install --user tox

    - command: tox
      args:
        chdir: "{{ zuul.project.src_dir }}"
