---

- hosts: all

  tasks:
    - shell: type tox || pip install --user tox

    - command: tox
      args:
        chdir: "{{ zuul.project.src_dir }}"
      environment:
        MOLECULE_DEBUG: true
